### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by gerhardsletten** [digitalocean/sample-nextjs#13]
Looking for a new hosting for a node websites, and are trying to understand how to run stuff on DO's app-platform, maybe save things like this to private projects..

![image](https://user-images.githubusercontent.com/63344/104480367-cc089e80-55c4-11eb-8bde-617922dc64a3.png)

**Comment by jonfriesen** [comment]
👋 @gerhardsletten 

This isn't a joke, but it definitely is our engineers having a bit of fun and sharing that fun with the community. In addition it shows how powerful our web console is!

![image](https://user-images.githubusercontent.com/2105302/104752461-8aced680-570b-11eb-93aa-68b6c5af4cec.png)

How cool is that!? Have a great weekend!
