### ISSUE TITLE
Redirects don't appear to be working

### ISSUE THREAD

**Issue by joneslloyd** [digitalocean/sample-nextjs#14]
Hi guys,

I've added a number of redirects to my `next.config.js` file, but they don't appear to be being honoured (I just get 404 pages).

There are no syntax issues, as the site builds without error.

Are redirects in `next.config.js` not supported by App Platform?

If not, what is the recommended method for redirects?

**Comment by kamaln7** [comment]
Hi @joneslloyd, are you running your Next.js site as a Service or Static Site? Next.js rewrites are only supported on the built-in Next.js server which is only used if your component is a Service. If it's a Static Site, the static export will be used instead without a running server.

**Comment by joneslloyd** [comment]
Hello,

I'm running it as a static site.

But when doing so with other 'hosts' like Vercel, the redirects still work
and are (I assume) handled via lambda functions.

Thanks,
Lloyd

**Comment by kamaln7** [comment]
At this time static sites do not support redirects, and the `next.config.js` redirects are only supported when running Next's built-in server ([docs](https://nextjs.org/docs/api-reference/next.config.js/redirects)), so you'll have to use a Service component to use the `next.config.js` redirects. Services would still benefit from the same CDN caching but the pricing might be a higher depending on the plan.

Another option is to configure next-router to handle these redirects on the client side. That way you can keep using the Static Site component. I found this plugin that might help: https://github.com/pablopunk/nextjs-redirect#static-export

There's also a related active RFC if you're interested: https://github.com/vercel/next.js/discussions/14890

I hope that helps!

**Comment by joneslloyd** [comment]
Ahh thank you for this info! Nice!
I will look into this.

(And sorry for the slow response)

**Comment by joneslloyd** [comment]
Sorry I was confused about that aspect:

I thought that DigitalOcean App Platform was an almost "1:1" replica of
Vercel with respect to how Next.js sites work.

So I assumed that static sites are served, but that 'server side' (lambda)
code is also respected.

Also thanks for the plugin! I'll check that out :)

Thanks,
Lloyd

**Comment by kamaln7** [comment]
Got it. No problem! Maybe in the future we can add support for lambas/functions to App platform—that would be cool :)
